-- app_data

CREATE USER app_data IDENTIFIED BY "23e3iSPbXJTCdxc"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_code
CREATE USER app_code IDENTIFIED BY "p4dGO4jSuYydFoS"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_admin
CREATE USER app_admin IDENTIFIED BY "uXzJ3aHo1kjNAyt"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS
ENABLE EDITIONS;

-- app_user
CREATE USER app_user IDENTIFIED BY "dPH921w8Q51whbC"
ENABLE EDITIONS;